### ISSUE TITLE
brands-sklep.pl | eazbiuro.pl | grafix.bialystok.pl | hurt100rowerow.pl | osaa.pl | pol-papier.pl | x-pak.pl

### ISSUE THREAD

**Issue by FadeMind** [FiltersHeroes/PolishSocialCookiesFiltersDev#116]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Edge Chromium

### Bloker

Bloker reklam AdGuard (Beta) 4.0.131

### Używane listy filtrów

Ad Blocking:
AdGuard Base

Privacy:
AdGuard Tracking Protection

Social Widgets:
AdGuard Social Media

Annoyances:
AdGuard Annoyances,
I don't care about cookies

Security:
Online Malicious URL Blocklist

Other:
AdGuard Experimental

Language-specific:
Official Polish filters for AdBlock, uBlock Origin & AdGuard,
Polish Social Filters,
KAD - Anti-Scam,
Polish Annoyances Filters,
Polish Anti Adblock Filters,
AlleBlock,
Polish Anti-Annoying Special Supplement

### Inne rozszerzenia

Polska Ciasteczkowa Zgoda 

### Link bezpośredni

```markdown
https://brands-sklep.pl/pl/product/47179,ekstraszeroka-podstawka-kensington-smartfit-kolor-czarny
```

### Dodatkowe informacje mogące mieć znaczenie

Adguard Devs uznali, że nie dodadzą fixa, bo mało ludzi tam wchodzi. 

`https://github.com/AdguardTeam/AdguardFilters/issues/111898`

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/5f6aa086e3b262443b84975b02cd9b0d7b9d1b9d

**Comment by krystian3w** [comment]
PR niby scalone, jak najdziesz jakieś nowe nazwy domen, bo 16 nie znamy bez opłacenia publicWWW lub NerdyData (hawkeye jak miał tam roczną opłatę to raczej jej nie przedłużył) to otwórz nowe zgłoszenie u MajkiIT.

**Comment by hawkeye116477** [comment]
> hawkeye jak miał tam roczną opłatę to raczej jej nie przedłużył

Nie miałem, jechałem jedynie na darmowym planie.
Jeszcze czego, miałby płacić  ponad 1 tyś rocznie za takie coś :stuck_out_tongue:
