### ISSUE TITLE
fesswybitnie.com i skladaniekomputera.pl, infogliwice.pl, nauka.rocks, webniusy.com

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#121]
Coś rozwala stronę (na dole)❓❓❓

**Comment by krystian3w** [comment]
Może webmaster, przy obecnym podejściu Google będzie trzeba prawie wszystko testować na ukrywanie skryptletem np. `set-constant` (fejkowe zgody).

**Comment by krystian3w** [comment]
Po mojej stronie raczej wygląda dobrze:

![1634290139975](https://user-images.githubusercontent.com/35370833/185472601-ef4066d8-4f26-45d3-a1d2-f8feb8f39ae4.jpg)

Może psuje generyk w dodatku Kiboke?

**Comment by krystian3w** [comment]
Wygląda na rozwalony Modal po otwarciu podurktu:

`###ct-ultimate-gdpr-cookie-modal`
