### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#123]
Blokada scrolla, w trybie incognito, żeby odblokować trzeba wyłączyć kosmetyczne i kliknąć "ok, zgadzam się" i po blokadzie tylko to irytuje, więc zgłaszam, np.:

`https://allegro.pl/kategoria/osobowe-bmw-4032?stan=u%C5%BCywane&p=4`

**Comment by krystian3w** [comment]
Wytyfy...?

**Comment by krystian3w** [comment]
@AdamWr wiesz coś o `scrollbar-gutter: stable`?

Taki CSS dodaje sztuczny "margines" na `main-wrapper`. Obecnie nie umiem samym overflow na body go niwelować.

Co do problemu ze brakiem przywracania przewijania to może to jest błąd tylko w lekko przestarzałym Comodo Dragon (jak dalej to jest na Chromium 102).

**Comment by AdamWr** [comment]
Szczerze mówiąc nie.
Jak się nie mylę to ten "margines" jest tylko w Chromium (nie widzę go w Firefoksie) i wygląda na to, że ustawienie `overflow: overlay` powoduje, że marginesu nie ma, ale z tego co widzę, to `overlay` jest "przestarzały", więc nie wiem, czy powinien być stosowany.
Zgaduję, że najprościej w takim przypadku będzie ustawić `scrollbar-gutter: auto`.
