### ISSUE TITLE
seriale tvp.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#127]
facebook ( button )

Oto kilka przykładów stron seriali:

```
barwyszczescia.tvp.pl##.container_tabs

mjakmilosc.tvp.pl##.container_tabs

nadobre.tvp.pl##.container_tabs

nasygnale.tvp.pl##.container_tabs

ojciecmateusz.tvp.pl##.container_tabs

komisarzalex.tvp.pl##.container_tabs

ranczo.tvp.pl##.container_tabs

```
A to zapewne że coś pominąłem i coś nowego pojawi się w przyszłości, dlatego proponuje dodać regułę ogólną : `tvp.pl##.container_tabs`

**Comment by krystian3w** [comment]
Gorzej jak wrzucą newsletter z trudną opcją rozdzielenia - wtedy pójdzie do dawnego RSS.

**Comment by blocker999** [comment]
To wymyśl inną lepszą i ogólną regułę

**Comment by krystian3w** [comment]
Reguły są do firewalla.

**Comment by krystian3w** [comment]
`###container_flyoutsocial a[href*="facebook.com/"]`
