### ISSUE TITLE
dziennik.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#129]
FB i TW (pod artykułami)  np.:

    https://sport.dziennik.pl/sporty-zimowe/artykuly/8683264,alpejski-ps-norwegowie-zawody-druzynowe.html

w różnych podstronach, dlatego proponuje dodać regułę ogólne:

```adb
dziennik.pl## .fb.social.button, .tw.social.button`
```

**Comment by krystian3w** [comment]
U nich może sprawdzić się samo .social lub pozbawione FB/TW jakby kiedyś dodali np. Instagram/wykop.
