### ISSUE TITLE
homebook.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#133]
tło

**Comment by krystian3w** [comment]
To i tak jest zamykane przez Ciasteczkową Polską Zgodę, bo nie ma stabilnego skryptletu dla uBo.

**Comment by krystian3w** [comment]
@kiboke, can you revert use `homebook.pl##.hb-layout ~ div` filter is now bad for ABP, uBo, AdGuard.

If you must kick Avast team for incompetence with add new filters to list and addon without your approve.

**Comment by kiboke** [comment]
@krystian3w It will be fixed, thanks for letting me know!
