### ISSUE TITLE
`###fb-root`

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#136]
To blokuje czaty a to nie sociale  

`czerwonak.pl,ekookna.pl,o-shop.com,quadralite.pl,selectshop.pl###fb-root`

**Comment by krystian3w** [comment]
To można przenieść do pliku: 

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/blob/master/sections/adblock_social_list/widgety_kontaktowe.txt#L21
