### ISSUE TITLE
eurogamer.pl

### ISSUE THREAD

**Issue by hawkeye116477** [FiltersHeroes/PolishSocialCookiesFiltersDev#142]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Linux/Unix

### Przeglądarka internetowa

Vivaldi 6.2.3105.58

### Bloker

uBlock Origin 1.52.2

### Używane listy filtrów

Wszystkie wymagane.

### Dodatkowe informacje mogące mieć znaczenie

Najwyraźniej już nie korzystają z OneTrust, więc trzeba wykombinować coś nowego albo podzielić się rewelacjami z ekipą gorhilla.

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Przydałby się najnowszy artykuł z zablokowanym wideo/teetem/facebookiem.

Pewnie z listy uBo cookie notices lub uBo annoyances ruszy:

```abp
eurogamer.*##+js(trusted-set-cookie, consentUUID, 7bb276c0-2469-4a2a-8264-61e7edf46065_25, 1year)
```

**Comment by krystian3w** [comment]
Mam testowo wpisy reddit w trybie txt zamiast ramki:

```md
https://www.eurogamer.pl/czesc-graczy-nie-moze-zainstalowac-marvels-spider-man-2-z-plyty
```

YouTube wygląda na załadowany.

**Comment by krystian3w** [comment]
uAssets niby w lipcu coś konserwowało:

https://github.com/uBlockOrigin/uAssets/commit/ed339b8a9cb92f8a80e72f3234a6600dbb441d24

Więc i u nas może trzeba to przerobić już na kilker by nie aktualizować często.

**Comment by krystian3w** [comment]
Zamykam jako za trudne do naprawienia standardowymi filtrami przekierowania/skryptletów lub HTML filteringu.

W uAssets Fin zaktualizował skryptlety by pop-up zniknął i Reddit nie był w trybie tekstowym a w dizajnerskiej ramce.
