### ISSUE TITLE
venezia.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#146]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

Blokada przewijania

**Comment by krystian3w** [comment]
@kiboke bad filter:

##.m-cookie-info:not(body):not(html)

fix:

`venezia.pl#@#.m-cookie-info:not(body):not(html)`

**Comment by krystian3w** [comment]
AdGuard Team recommend tests:

```adb
/cookie-info.
```

**Comment by kiboke** [comment]
@krystian3w sorry to inform you that I don't work on IDCAC from now on. It has been acquired by GEN Digital Inc. a couple of years ago and it's now under their full control. Thank you for all your help so far!
