### ISSUE TITLE
selgros.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#147]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

blokada przewijania

**Comment by krystian3w** [comment]
Dokładny URL, bo taki jest OK:

`https://www.selgros.pl/`

**Comment by krystian3w** [comment]
@kiboke these looks are bad for Chromium (e.g. Edge):
```adb
###klaro div[class*="cookie-notice"]
##.cookie-notice:not(body):not(html):not(#wrapper):not(#footer)
```

Fix:

```adb
selgros.pl#@##klaro div[class*="cookie-notice"]
selgros.pl#@#.cookie-notice:not(body):not(html):not(#wrapper):not(#footer)
```

Maybe again possible repair scroll with network filtering files/requests.

**Comment by kiboke** [comment]
@krystian3w please stop tagging me, I don't participate in maintaining the IDCAC extension anymore. Thanks :slightly_smiling_face:
