### ISSUE TITLE
stilord.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#148]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [x] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

resztka: tło

**Comment by krystian3w** [comment]
Tło mam z cookies, gdzie z socjal mediów.

**Comment by krystian3w** [comment]
@kiboke check these:

```adb
###cookie-overlay:empty
```
