### ISSUE TITLE
gorteks.com.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishSocialCookiesFiltersDev#149]
Nie działa przewijanie

Zgłoszenie opublikowane przez użytkownika **ytg**.

**Comment by krystian3w** [comment]
Mogę spróbować dodać na początku `body/HTML` z negacją klasy/id/style, gdy blokada pliku JS jest wciąż zła.

Na pewno pop-upy tego silnika sklepu są problematyczne gdy twórcy nie przełączyli się na najnowszą wersję skryptu (w użyciu są minimum dwie a z 5 lat temu była jeszcze inna).
