### ISSUE TITLE
[OneTrust] `nintendo.*,~pl`

### ISSUE THREAD

**Issue by piquark6046** [FiltersHeroes/PolishSocialCookiesFiltersDev#150]
### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Brave

### Bloker (Blocker)

AdGuard Browser Extension 4.3.13

### Używane listy filtrów (Used filter lists)

1. AdGuard Base filters list
2. ADGuard Tracking protection filters list
3. AdGuard URL tracking filters list
4. AdGuard Annoyance filters list
5. Polish Annoyances Filters list

### Link bezpośredni (A specific URL)

```markdown
https://www.nintendo.co.uk/
```

### Opis błędu (A bug description)

If Polish Annoyances Filters list and AdGuard Annoyance filters list are enabled, the cookie popup will appear.
However, if Polish Annoyances Filters list is disabled, the popup will not appear.

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

https://github.com/AdguardTeam/AdguardFilters/issues/173686

**Comment by krystian3w** [comment]
I limited OneTrust exceptions to Polish range:

```yml
avanti24.pl
bankier.pl
bethesda.net
blaklader.pl
carrefour.pl
cartoonito.pl
czterykaty.pl
dyskusje24.pl
edziecko.pl
elle.pl
elleman.pl
essilor.pl
focus.pl
focusnauka.pl
g.pl
gazeta.pl
gazeta.tv
glamour.pl
gry.pl
haps.pl
hapsvod.pl
ikea.com
infoladnydom.pl
infozdrowie24.pl
kobieta.pl
magazyn-kuchnia.pl
mojegotowanie.pl
mojpieknyogrod.pl
moto-wiadomosci.pl
moto.pl
national-geographic.pl
olx.pl
pizzahut.pl
player.pl
plotek.pl
przyslijprzepis.pl
sport.gwar.pl
sport.pl
tokfm.pl
toteraz.pl
tvn.pl
tvn24.pl
ugotuj.to
wpodrozy24.pl
wyborcza.pl
```

The change will probably reach AdGuard after 4 March when it is uploaded to the RODO-cookie list in the MajkiIT repository on 2 March.
