### ISSUE TITLE
aldi.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishSocialCookiesFiltersDev#151]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 122.0.6261.69
**Bloker:** AdGuard 4.3.13
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Blokuje scrollowanie strony

Zgłoszenie opublikowane przez użytkownika **trd**.

**Comment by hawkeye116477** [comment]
Zgadza się, bez ELC, które blokuje skrypt. Jednak lista AdGuard cookies daje wyjątek na ten skrypt na stronę Aldiego, bo były problemy => https://github.com/AdguardTeam/AdguardFilters/issues/154859.

**Comment by krystian3w** [comment]
Połączyłem CSS z linią cewe i spółka, chyba że serio masz blokadę przewijania na tagu html bez użycia klasy `.overflowHidden`.
