### ISSUE TITLE
lzx.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#160]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [X] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker

uBlock Origin 1.57.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Link bezpośredni

```Markdown
https://lzx.pl/login
```

### Dodatkowe informacje mogące mieć znaczenie

Polskie sociale usuwają literke "f" na niebieskim kwadraciku - ( logowanie przez facebooka )

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
To jest raczej twój błąd lub Majkela - filtr jest stary:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/6262625d7d5e60d572034e5db82aaba821227d88
