### ISSUE TITLE
sprzedajemy.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#161]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [X] Element społecznościowy
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Firefox 125.0.2 (64-bitowa)

### Bloker

uBlock Origin 1.57.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Link bezpośredni

```Markdown
https://sprzedajemy.pl/cabrio-bmw-328i-super-auto-siemiatycze-4-6bea9f-nr69216003
```

### Dodatkowe informacje mogące mieć znaczenie

FB i X (pod zdjęciem)

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Ja mam tylko e-mail w Firefox 125.0.3:

![obraz](https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/assets/35370833/a193dad0-a7b9-46d0-a916-26cba3fcc90e)

![obraz](https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/assets/35370833/a72461e9-feb6-40d3-8090-fe02c8bee2b4)

Więc musiałby sprawdzić @hawkeye116477 na AMD w Vivaldi.

Nie kojarzę by jakiś nowy filtr dev to wycinał.

**Comment by krystian3w** [comment]
Portal może oferować jakieś testy A/B nowego wyglądu jak się im nudzi tak jak w Googlu.
