### ISSUE TITLE
e-pity.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishSocialCookiesFiltersDev#166]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 125.0.6422.112
**Bloker:** AdGuard 4.3.46
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Strony nie chcą się załadować
https://www.e-pity.pl/pit-online/
https://www.fillup.pl/online/
https://www.fillup.pl/firmly/online/
![](https://i.imgur.com/pHr0ysQ.png)

Zgłoszenie opublikowane przez użytkownika **zfs**.

**Comment by krystian3w** [comment]
Najwidoczniej nie można wycinać pop-upa:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/blob/c676efc6f41002e9b7aaab7e051e3afa4a4270f6/sections/adblock_cookies/specyficzne_ukrywajace.txt#L808

Jak nie da się przerwać akcji standardowym arsenałem ani zaakceptować to pewnie trzeba będzie doinstalować w trybie polis PCC/PCZ (jak nie jest to osobny iframe i ma status low visitors by AdamWr tracił czas na regułę z JS).
