### ISSUE TITLE
wieszgdziezwierz.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#167]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 123.0.6312.123 (64-bitowa)

### Bloker

uBlock Origin 1.58.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie

cookies - scrollujący  pasek ( na dole )

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Przecież można do majkela zgłaszać, nazwa strony nie wskazuje że jest w top 100.
