### ISSUE TITLE
sorted.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishSocialCookiesFiltersDev#169]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 126.0.6478.126
**Bloker:** AdGuard 4.3.53
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/olRXser.png)

Zgłoszenie opublikowane przez użytkownika **xfr**.

**Comment by hawkeye116477** [comment]
Właściwie to on ma niby też jakiś formularz na swojej stronce => https://www.certyficate.it/zglos-reklame/, ale nie wiem czy to coś jeszcze działa.

**Comment by krystian3w** [comment]
Raczej nie wrócił do łask.

Teoretycznie można przemyśleć czy przebudować filtr przeciw wtyczce YesCookie:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/blob/6cc7ff71fcbe6ad69f1ddfeadadd9679363ad50b/sections/adblock_cookies/ogolne_ukrywajace.txt#L115

(np. usunięcie `:not(.cli-bar-popup):not(.cli-modal-content)` gdy sprawdzamy body).

Z blokadą tła globalnie.
