### ISSUE TITLE
nowe ogólne filtry na ciasteczka

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#175]
### Dodatkowe informacje mogące mieć znaczenie

Proponuje dodać do paczki następujące filtry: 

```adb
pl###cookie

pl###cookies

pl###notice_bar

pl##.config-messages

pl##.configMessages

pl##.bm-privacy

pl##.cookie

pl##.cookies

pl##.head-page-information
```

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Ja jestem na nie, część to mechanizm na pasek powiadomień (sklepy Comarch  z ich `config-messages` / `configMessages`) i ich lub niebezpieczne filtry (`.cookie` / `.cookies`).

**Comment by krystian3w** [comment]
Ostatni filtr jest od ponad 6 lat: https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/6f78846a7abc7cc9877568883e3adedd9776bb62#diff-6f98407a7a986519cd07d449bef61e175604f80f079ed19e531ad016b0e55c9bR188
