### ISSUE TITLE
`##.socializer-whatsapp`

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#178]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [X] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 125.0.6422.142 (32-bitowa)

### Bloker

uBlock Origin 1.60.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie

Do ponownego przejrzenia i decyzji co zostawić a co usunąć: 

`socializer-whatsapp`

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/discussions/113#discussioncomment-2028143 - można połączyć w jedno 2 wystąpienia.
