### ISSUE TITLE
konskowola.info.pl###privacy_info_content

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#179]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 125.0.6422.142 (32-bitowa)

### Bloker

uBlock Origin 1.60.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie

dwa razy to samo, po co ?

`konskowola.info.pl###privacy_info_content` 

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by hawkeye116477** [comment]
Ja tu widzę tylko jedno wystąpienie.

**Comment by krystian3w** [comment]
Najwidoczniej kiedyś nie blokowali klikania/przewijania.
