### ISSUE TITLE
nowe ogólne filtry na ciasteczka    cz. II

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#180]
```adb
pl###cookie-rp

pl##.ba_cookie_bar

pl##.cookie-box

pl##.cookies-tab

pl##.r-cookie-bar

pl##.terms-cookies
```

może blokuje przewijanie/klikanie/multimedia:
```adb
pl###pdcookielaw
```

wygląda na losowy:

```adb
pl##.fmessages.container
```

Dodane inaczej:
```diff
+++ pl##.fscookies-overlay
```

**Comment by krystian3w** [comment]
Po co część 2 jak nie zamknął hawkeye116477 pierwszej.

**Comment by krystian3w** [comment]
Te wydają się lepsze poza `pl##.fmessages.container` - znów może mieć byle co wpisane i brak detekcji innej niż `has-text`.
