### ISSUE TITLE
gmina-aleksandrow.pl###g_toplayer

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#181]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [X] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [ ] Element społecznościowy
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [x] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 125.0.6422.142 (32-bitowa)

### Bloker

uBlock Origin 1.60.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie

( duble )

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
To się nie nadaje do ciasteczek jako ogólne.
