### ISSUE TITLE
ZPR Media `##.messenger`

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#182]
### Dodatkowe informacje mogące mieć znaczenie

Do przejrzenia - (komunikatory)

**Comment by krystian3w** [comment]
Potrzebne prawdziwe przykłady zepsutych stron (np. całe białe, z zablokowanym przewijaniem, bo filtr zablokował jakiś pop-up).

Nie sądzę by domeny usunęły czat lub funkcje udostępniania linka na messengera w PW/DM.

#111 #113
