### ISSUE TITLE
pfron.org.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishSocialCookiesFiltersDev#183]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [X] Element społecznościowy
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie
- [ ] Redundancja

### System operacyjny

Windows

### Przeglądarka internetowa

Comodo Dragon Version 129.0.6668.90 (32-bitowa)

### Bloker

uBlock Origin 1.61.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie

brak obrazka 

![pf](https://github.com/user-attachments/assets/4e259ea8-1e9b-4762-bda1-e4b48447750c)

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
To stary filtr:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/4328d3277c5ac860372531740e69e2c859744f40#diff-26b08022ed92c58d13b6ff29fc4f64c8fba9831f16bb05cccc7f0911cca0251aL605
